# Generated by Django 2.2 on 2019-10-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_modelblog_texto_breve'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelblog',
            name='url_image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
