# Generated by Django 2.2 on 2019-11-10 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_modelcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcontact',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
