# Generated by Django 2.2 on 2019-10-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_modelblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelblog',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='modelblog',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
