# Generated by Django 2.2 on 2019-10-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191006_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelblog',
            name='texto_breve',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='modelblog',
            name='url_image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
