# Generated by Django 2.2 on 2019-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191020_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mensaje', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
